### ISSUE TITLE
pox issue

### ISSUE THREAD

**Issue by saptarsi96** [arunnair018/DDoS-detection-and-mitigation-in-SDN-controller#1]
While running `$ ./pox.py forwarding.l3` getting the following error. Can you please guide me?
```
POX 0.7.0 (gar) / Copyright 2011-2020 James McCauley, et al.
Traceback (most recent call last):
  File "/home/saptarsi/pox/pox/boot.py", line 74, in do_import2
    __import__(name, level=0)
  File "/home/saptarsi/pox/pox/forwarding/l3.py", line 45, in <module>
    from .detect_v1 import associate
ModuleNotFoundError: No module named 'pox.forwarding.detect_v1'
Could not import module: forwarding.l3
```

**Comment by dk1242** [comment]
@saptarsi96 did you get the solution, I am getting a similar error.
